// src/hooks/use-tier-generation.ts
// ============================================================================
// useTierGeneration — AI Tier Prompt Generation (Call 2) v4.0.0
// ============================================================================
// v4.0.0 (12 Apr 2026): Phase B — 3-tier output (T2 removed)
//   - ApiResponse drops tier2 (MJ moves to Call T2, Phase C)
//   - apiToGeneratedPrompts sets tier2/negative.tier2 to empty string
//     for backward compatibility (saved prompts, EEP rendering)
//   - validateTiers checks tier1/tier3/tier4 only
// v3.0.0 (13 Apr 2026): Phase A — engine-fill removed, coverageSeed added
//   - fill: "engine" no longer accepted (P1: user is only source of creative intent)
//   - coverageSeed param added — forwards Call 1's phrase→category mapping
//     to the route for anatomy array preparation (Phase B)
//   - No user-visible behaviour change yet — coverageSeed is prep only
// v2.0.0 (5 Apr 2026): Resilience layer
//   - Auto-retry once on transient errors (network, format, rate limit)
//   - No retry on content policy violations
//   - Tier validation: at least 1 tier must have non-empty positive content
//   - Error type classification for UI routing
//   - 1.5s delay before retry (avoids hammering on rate limits)
//
// Calls POST /api/generate-tier-prompts to generate all 4 tier prompts
// directly from the user's human text description.
//
// Authority: ai-disguise.md §5 (Call 2 — AI Tier Generation)
// Existing features preserved: Yes — same return type, same API contract.
// ============================================================================

'use client';

import { useState, useCallback, useRef } from 'react';
import type { GeneratedPrompts, TierAnatomy } from '@/types/prompt-intelligence';
import type { CoverageSeed } from '@/types/category-assessment';
import type { AnatomySegment } from '@/types/prompt-intelligence';

// ============================================================================
// TYPES
// ============================================================================

export interface TierGenerationProviderContext {
  tier: number;
  name: string;
  promptStyle: string;
  sweetSpot: number;
  tokenLimit: number;
  qualityPrefix?: string[];
  weightingSyntax?: string;
  supportsWeighting?: boolean;
  negativeSupport: 'separate' | 'inline' | 'none' | 'converted';
}

/** Error types for UI routing */
export type TierErrorType = 'content-policy' | 'rate-limit' | 'network' | 'format' | 'validation' | 'unknown';

export interface TierGenerationError {
  type: TierErrorType;
  message: string;
  /** Whether the error is retryable (false for content policy) */
  retryable: boolean;
}

export interface UseTierGenerationReturn {
  aiTierPrompts: GeneratedPrompts | null;
  /** Phase B: per-tier anatomy arrays — separate from prompts to keep dynamic access clean */
  tierAnatomy: TierAnatomy | null;
  isGenerating: boolean;
  error: TierGenerationError | null;
  generatedForProvider: string | null;
  generatedForProviderId: string | null;
  generate: (
    sentence: string,
    providerId: string | null,
    providerContext: TierGenerationProviderContext | null,
    gapIntent?: 'all-satisfied' | 'skipped' | 'user-decided',
    categoryDecisions?: Array<{ category: string; fill: string }>,
    coverageSeed?: CoverageSeed[],
  ) => Promise<boolean>;
  clear: () => void;
}

// ============================================================================
// API RESPONSE SHAPE
// ============================================================================

interface ApiTierOutput {
  positive: string;
  negative: string;
  anatomy?: AnatomySegment[];
}

interface ApiResponse {
  tiers: {
    tier1: ApiTierOutput;
    tier3: ApiTierOutput;
    tier4: ApiTierOutput;
  };
}

// ============================================================================
// CONSTANTS
// ============================================================================

/** Delay before auto-retry (ms) */
const RETRY_DELAY = 1500;

// ============================================================================
// HELPERS
// ============================================================================

function apiToGeneratedPrompts(api: ApiResponse['tiers']): GeneratedPrompts {
  return {
    tier1: api.tier1.positive,
    // Phase B: T2 no longer generated by Call 2. Use T3 prose as the
    // deterministic MJ "before" state — user sees their content as plain
    // prose. Call T2 (Phase C) will transform this into MJ-native syntax.
    tier2: api.tier3.positive,
    tier3: api.tier3.positive,
    tier4: api.tier4.positive,
    negative: {
      tier1: api.tier1.negative,
      tier2: '', // MJ negatives come from Call T2 (Phase C), not Call 2
      tier3: api.tier3.negative,
      tier4: api.tier4.negative,
    },
  };
}

/** Extract anatomy arrays from API response — separate from prompt strings */
function extractAnatomy(api: ApiResponse['tiers']): TierAnatomy | null {
  const hasAny = api.tier1.anatomy || api.tier3.anatomy || api.tier4.anatomy;
  if (!hasAny) return null;
  return {
    ...(api.tier1.anatomy ? { tier1: api.tier1.anatomy } : {}),
    ...(api.tier3.anatomy ? { tier3: api.tier3.anatomy } : {}),
    ...(api.tier4.anatomy ? { tier4: api.tier4.anatomy } : {}),
  };
}

/** Validate that at least 1 tier has non-empty positive content */
function validateTiers(prompts: GeneratedPrompts): boolean {
  return !!(
    prompts.tier1?.trim() ||
    prompts.tier3?.trim() ||
    prompts.tier4?.trim()
  );
}

/** Classify error type from HTTP status and response body */
function classifyTierError(
  status: number,
  errorCode?: string,
  message?: string,
): TierGenerationError {
  const msg = message ?? 'Something went wrong. Please try again.';

  if (errorCode === 'CONTENT_POLICY' || status === 451) {
    return { type: 'content-policy', message: 'Your description may contain restricted content. Try different wording.', retryable: false };
  }
  if (status === 429 || errorCode === 'RATE_LIMITED') {
    return { type: 'rate-limit', message: 'Busy — retrying...', retryable: true };
  }
  if (status === 0) {
    return { type: 'network', message: 'Connection issue — retrying...', retryable: true };
  }
  if (msg.toLowerCase().includes('format') || msg.toLowerCase().includes('parse')) {
    return { type: 'format', message: 'Algorithm hiccup — retrying...', retryable: true };
  }
  return { type: 'unknown', message: 'Algorithm overload — retrying...', retryable: true };
}

/** Wait for a specified duration */
function wait(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ============================================================================
// SINGLE ATTEMPT — extracted for retry logic
// ============================================================================

interface AttemptResult {
  ok: boolean;
  prompts?: GeneratedPrompts;
  anatomy?: TierAnatomy | null;
  error?: TierGenerationError;
}

async function attemptGenerate(
  requestBody: Record<string, unknown>,
  signal: AbortSignal,
): Promise<AttemptResult> {
  const res = await fetch('/api/generate-tier-prompts', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(requestBody),
    signal,
  });

  if (signal.aborted) return { ok: false };

  if (!res.ok) {
    let data: { error?: string; message?: string } = {};
    try { data = await res.json(); } catch { /* ignore */ }
    return { ok: false, error: classifyTierError(res.status, data.error, data.message) };
  }

  const data: ApiResponse = await res.json();

  if (!data.tiers) {
    return { ok: false, error: { type: 'format', message: 'No prompts returned. Please try again.', retryable: true } };
  }

  const prompts = apiToGeneratedPrompts(data.tiers);
  const anatomy = extractAnatomy(data.tiers);

  // Validate: at least 1 tier must have content
  if (!validateTiers(prompts)) {
    return { ok: false, error: { type: 'validation', message: 'Generated prompts were empty. Please try again.', retryable: true } };
  }

  return { ok: true, prompts, anatomy };
}

// ============================================================================
// HOOK
// ============================================================================

export function useTierGeneration(): UseTierGenerationReturn {
  const [aiTierPrompts, setAiTierPrompts] = useState<GeneratedPrompts | null>(null);
  const [tierAnatomy, setTierAnatomy] = useState<TierAnatomy | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<TierGenerationError | null>(null);
  const [generatedForProvider, setGeneratedForProvider] = useState<string | null>(null);
  const [generatedForProviderId, setGeneratedForProviderId] = useState<string | null>(null);

  const abortRef = useRef<AbortController | null>(null);
  // Generation counter — only the latest generation's results are accepted.
  // Eliminates abort race condition where old response arrives after new call starts.
  const generationIdRef = useRef(0);

  const generate = useCallback(
    async (
      sentence: string,
      providerId: string | null,
      providerContext: TierGenerationProviderContext | null,
      gapIntent?: 'all-satisfied' | 'skipped' | 'user-decided',
      categoryDecisions?: Array<{ category: string; fill: string }>,
      coverageSeed?: CoverageSeed[],
    ): Promise<boolean> => {
      const trimmed = sentence.trim();
      if (!trimmed) {
        setError({ type: 'unknown', message: 'No description provided.', retryable: false });
        return false;
      }

      // Cancel any in-flight request
      if (abortRef.current) {
        abortRef.current.abort();
      }
      const controller = new AbortController();
      abortRef.current = controller;

      // Increment generation ID — stale responses from older calls are rejected
      generationIdRef.current += 1;
      const thisGenerationId = generationIdRef.current;

      setIsGenerating(true);
      setError(null);

      try {
        const requestBody: Record<string, unknown> = {
          sentence: trimmed,
          providerId,
          providerContext,
        };
        if (gapIntent) requestBody.gapIntent = gapIntent;
        if (categoryDecisions && categoryDecisions.length > 0) {
          requestBody.categoryDecisions = categoryDecisions;
        }
        if (coverageSeed && coverageSeed.length > 0) {
          requestBody.coverageSeed = coverageSeed;
        }

        // ── Attempt 1 ──────────────────────────────────────────────
        const first = await attemptGenerate(requestBody, controller.signal);

        // Reject if aborted OR a newer generation has started
        if (controller.signal.aborted || generationIdRef.current !== thisGenerationId) return false;

        if (first.ok && first.prompts) {
          setAiTierPrompts(first.prompts);
          setTierAnatomy(first.anatomy ?? null);
          setGeneratedForProvider(providerContext?.name ?? null);
          setGeneratedForProviderId(providerId);
          setIsGenerating(false);
          return true;
        }

        // ── Check if retryable ─────────────────────────────────────
        if (!first.error?.retryable) {
          // Content policy — don't retry, show error immediately
          setError(first.error ?? { type: 'unknown', message: 'Generation failed.', retryable: false });
          setIsGenerating(false);
          return false;
        }

        // ── Auto-retry after delay ─────────────────────────────────
        console.debug('[PromptAlgorithm] Attempt 1 failed, retrying in', RETRY_DELAY, 'ms...');
        await wait(RETRY_DELAY);

        if (controller.signal.aborted || generationIdRef.current !== thisGenerationId) return false;

        const second = await attemptGenerate(requestBody, controller.signal);

        if (controller.signal.aborted || generationIdRef.current !== thisGenerationId) return false;

        if (second.ok && second.prompts) {
          setAiTierPrompts(second.prompts);
          setTierAnatomy(second.anatomy ?? null);
          setGeneratedForProvider(providerContext?.name ?? null);
          setGeneratedForProviderId(providerId);
          setIsGenerating(false);
          return true;
        }

        // ── Both attempts failed ───────────────────────────────────
        const finalError = second.error ?? first.error ?? {
          type: 'unknown' as TierErrorType,
          message: 'Something went wrong. Please try again.',
          retryable: true,
        };
        // Override message for user-facing display after retry exhausted
        setError({
          ...finalError,
          message: finalError.type === 'rate-limit'
            ? 'Service is busy. Please try again in a moment.'
            : 'Something went wrong. Your free prompt is still available — try again.',
        });
        setIsGenerating(false);
        return false;
      } catch (err) {
        if (err instanceof DOMException && err.name === 'AbortError') {
          return false;
        }
        console.error('[PromptAlgorithm] Error:', err);
        setError({ type: 'network', message: 'Connection failed. Your free prompt is still available — try again.', retryable: true });
        setIsGenerating(false);
        return false;
      }
    },
    [],
  );

  const clear = useCallback(() => {
    setAiTierPrompts(null);
    setTierAnatomy(null);
    setError(null);
    setGeneratedForProvider(null);
    setGeneratedForProviderId(null);
  }, []);

  return {
    aiTierPrompts,
    tierAnatomy,
    isGenerating,
    error,
    generatedForProvider,
    generatedForProviderId,
    generate,
    clear,
  };
}
