// src/lib/call-2-harness/mechanical-scorer/t2-rules.ts
// ============================================================================
// T2 (Midjourney Family) Mechanical Rules
// ============================================================================
// Phase B update: T2 is no longer generated by Call 2. tier2.positive will
// be an empty string. All T2 rules detect this and return passed: true with
// a SKIPPED note — they do not report false failures. This keeps pass/fail
// counts clean and the inventory/diff system accurate.
//
// When Call T2 ships (Phase C), these rules will be re-activated by routing
// them to the Call T2 output instead of the Call 2 tier2 field.
//
// Cluster mapping per architecture §10.1 (cluster-schema-v1).
// ============================================================================

import type { RuleDefinition, RuleCheckOutput, TierBundle } from './types';

// ── Helpers ────────────────────────────────────────────────────────────────

/** Phase B: T2 is no longer generated by Call 2. Skip rule if tier2 is empty
 *  or contains prose fallback (T3 copy) with no MJ-native syntax. */
const SKIP_EMPTY = 'SKIPPED: T2 empty — not generated by Call 2 (Phase B)';
const SKIP_PROSE = 'SKIPPED: T2 is prose fallback — no MJ syntax (Phase B, awaiting Call T2)';

function skipIfNotMjNative(bundle: TierBundle): RuleCheckOutput | null {
  const t2 = bundle.tier2.positive.trim();
  if (!t2) return { passed: true, details: SKIP_EMPTY };
  // Phase B: T2 may contain T3 prose copy with no MJ-specific syntax.
  // Real MJ content has :: weight clauses or -- parameters.
  const hasMjSyntax = /::[\d.]/.test(t2) || /--(?:ar|v|s|no)\s/.test(t2);
  if (!hasMjSyntax) return { passed: true, details: SKIP_PROSE };
  return null; // MJ-native content present — run the real check
}

/**
 * Find the start index of the parameter section (where --ar/--v/--s/--no
 * begins). Returns -1 if no parameter section is present.
 */
function findParamSectionStart(text: string): number {
  return text.search(/\s--(?:ar|v|s|no)\s/);
}

function getProseSection(text: string): string {
  const idx = findParamSectionStart(text);
  return idx === -1 ? text : text.slice(0, idx);
}

// ── Rule definitions ───────────────────────────────────────────────────────

export const T2_RULES: readonly RuleDefinition[] = Object.freeze([
  // ── R1: --ar present ────────────────────────────────────────────────────
  {
    id: 'T2.ar_param_present',
    tier: 2,
    cluster: 'syntax_leak',
    description: 'T2 must include --ar with an aspect ratio (e.g. --ar 16:9).',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      if (!/--ar\s+\d+:\d+/.test(bundle.tier2.positive)) {
        return { passed: false, details: 'Missing --ar parameter' };
      }
      return { passed: true };
    },
  },

  // ── R2: --v present ─────────────────────────────────────────────────────
  {
    id: 'T2.v_param_present',
    tier: 2,
    cluster: 'syntax_leak',
    description: 'T2 must include --v with a version number (e.g. --v 7).',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      if (!/--v\s+\d+/.test(bundle.tier2.positive)) {
        return { passed: false, details: 'Missing --v parameter' };
      }
      return { passed: true };
    },
  },

  // ── R3: --s present ─────────────────────────────────────────────────────
  {
    id: 'T2.s_param_present',
    tier: 2,
    cluster: 'syntax_leak',
    description: 'T2 must include --s with a stylize value (e.g. --s 500).',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      if (!/--s\s+\d+/.test(bundle.tier2.positive)) {
        return { passed: false, details: 'Missing --s parameter' };
      }
      return { passed: true };
    },
  },

  // ── R4: --no present ────────────────────────────────────────────────────
  {
    id: 'T2.no_param_present',
    tier: 2,
    cluster: 'negative_handling_leak',
    description: 'T2 must include --no with negative terms (without --no, MJ treats negatives as positives).',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      if (!/--no\s+\S/.test(bundle.tier2.positive)) {
        return { passed: false, details: 'Missing --no block' };
      }
      return { passed: true };
    },
  },

  // ── R5: --no exactly once (the rescue-dependency canary) ────────────────
  {
    id: 'T2.no_exactly_once',
    tier: 2,
    cluster: 'negative_handling_leak',
    description: 'The --no flag must appear EXACTLY ONCE in T2 — duplicate --no blocks are the canonical model bug.',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      const matches = bundle.tier2.positive.match(/--no\s/g);
      const count = matches?.length ?? 0;
      if (count !== 1) {
        return {
          passed: false,
          details: `--no appears ${count} times, expected exactly 1`,
        };
      }
      return { passed: true };
    },
  },

  // ── R6: ≥3 weighted :: clauses ──────────────────────────────────────────
  {
    id: 'T2.weight_clauses_min_3',
    tier: 2,
    cluster: 'syntax_leak',
    description: 'T2 must contain at least 3 weighted :: clauses in the prose section.',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      const prose = getProseSection(bundle.tier2.positive);
      const matches = prose.match(/::\d+\.\d+/g);
      const count = matches?.length ?? 0;
      if (count < 3) {
        return {
          passed: false,
          details: `${count} weighted :: clauses, expected ≥3`,
        };
      }
      return { passed: true };
    },
  },

  // ── R7: no mid-phrase weights ───────────────────────────────────────────
  {
    id: 'T2.no_mid_phrase_weights',
    tier: 2,
    cluster: 'syntax_leak',
    description: 'Place :: weights at the END of complete clauses, never mid-phrase.',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      const prose = getProseSection(bundle.tier2.positive);
      // After ::N.N, the next non-whitespace char must be a comma or end-of-prose.
      // If there are non-comma word characters following, that's mid-phrase.
      const violations: string[] = [];
      for (const m of prose.matchAll(/::\d+\.\d+([^,]*)/g)) {
        const after = (m[1] ?? '').trim();
        if (after.length > 0) {
          violations.push(`::${m[0]} ${after.slice(0, 30)}`);
        }
      }
      if (violations.length > 0) {
        return {
          passed: false,
          details: `Mid-phrase weight: ${violations[0]}`,
        };
      }
      return { passed: true };
    },
  },

  // ── R8: T2 negative JSON field is empty (v4.4 root-cause fix) ───────────
  {
    id: 'T2.empty_negative_json_field',
    tier: 2,
    cluster: 'negative_handling_leak',
    description: 'T2 negative JSON field must be empty string. All negatives go inline after --no in the positive field.',
    check(bundle) {
      const skip = skipIfNotMjNative(bundle);
      if (skip) return skip;
      if (bundle.tier2.negative !== '') {
        return {
          passed: false,
          details: `T2.negative is non-empty: "${bundle.tier2.negative.slice(0, 40)}..."`,
        };
      }
      return { passed: true };
    },
  },
]);
