// src/__tests__/routes.providers.test.ts
//
// Metadata tests for provider routes.
// Authority: docs/authority/prompt-builder-page.md
//
// Architecture note: The prompt-builder route (/providers/[id]/prompt-builder)
// is now a redirect to /providers/[id]. Metadata is only generated by the
// provider detail page.

import type { Metadata } from 'next';
import { getProviderById, PROVIDERS } from '@/data/providers';
import { generateMetadata as generateProviderDetailMetadata } from '@/app/providers/[id]/page';

function getTestProvider() {
  const preferred = getProviderById('openai');
  const fallback = PROVIDERS[0];

  const provider = preferred ?? fallback;
  if (!provider) {
    throw new Error('No providers found in catalogue (PROVIDERS is empty).');
  }

  return provider;
}

function normaliseTitle(title: Metadata['title']): string | undefined {
  if (!title) return undefined;
  if (typeof title === 'string') return title;

  // Next allows objects like { absolute: string } and template shapes.
  if (typeof title === 'object' && 'absolute' in title && typeof title.absolute === 'string') {
    return title.absolute;
  }

  return undefined;
}

describe('providers routes — metadata', () => {
  it('generates provider detail metadata with prompt builder title', async () => {
    const provider = getTestProvider();

    const metadata = await generateProviderDetailMetadata({ params: { id: provider.id } });
    const title = normaliseTitle(metadata.title);

    // Provider detail page now includes prompt builder functionality
    expect(title).toBe(`${provider.name} prompt builder • Promagen`);
  });

  it('generates not-found metadata for unknown provider', async () => {
    const metadata = await generateProviderDetailMetadata({
      params: { id: 'unknown-provider-xyz' },
    });
    const title = normaliseTitle(metadata.title);

    expect(title).toBe('Provider not found • Promagen');
  });
});
