// src/lib/weather/tier-generators.ts
// ============================================================================
// TIER GENERATORS — 4 Prompt Output Formats
// ============================================================================
//
// v9.2.0 (20 Feb 2026) — Chat 3: Camera/Lens + Negatives + Quality Tags
// - Camera body + lens metadata wired into all 4 tiers
// - Platform-aware negative prompts (T1: CLIP tokens, T2: --no fix, T3: inline)
// - Richer quality tags per platform (camera spec replaces generic adjectives)
//
// v9.0.0: Extracted from weather-prompt-generator.ts (4,311-line monolith)
// Existing features preserved: Yes
// ============================================================================

import type { ExchangeWeatherFull } from './weather-types';
import { capitalize, hashString } from './prng';
import type {
  PromptProfile,
  WeatherPromptResult,
  LightingState,
  VisualTruth,
  VenueResult,
} from './prompt-types';
import { VERBOSITY_T1_LIMIT, VERBOSITY_T4_LIMIT } from './prompt-types';
import {
  getMoisturePhrase,
  getThermalPhrase,
  getSurfaceGrounding,
  composeLightingSentence,
  composeSurfaceSentence,
  getLightReflectionNoun,
} from './visual-truth';
import {
  getTempPhrase,
  getHumidityPhrase,
  getTimeDescriptor,
  getSkySourceAware,
  getSettingEnding,
  getTimePeriod,
  buildContext,
} from './vocabulary-loaders';
import { getWindPhrase } from './wind-system';
import { shouldExcludePeople, getSolarPhaseLabel, type SolarPhase } from './time-utils';
import { getUrbanLightFactor } from './lighting-engine';
import { getCloudTypePhrase } from './cloud-types';
import type { CloudType } from './cloud-types';
import {
  getCameraLens,
  getNegativeT1,
  getMjNoParam,
  getQualityTagsT1,
  getQualityT2,
  getQualityEndingT3,
  getQualityT4,
} from './camera-lens';

// ============================================================================
// SHARED SEED COMPUTATION
// ============================================================================

export function computeSeed(
  ctx: ReturnType<typeof buildContext>,
  hour: number,
  observedAtUtc: Date,
  city: string,
): number {
  const twoHourWindow = Math.floor(observedAtUtc.getTime() / 7_200_000);
  return (
    ctx.tempC * 100 + ctx.humidity * 10 + ctx.windKmh + hour + twoHourWindow + hashString(city)
  );
}

// ============================================================================
// v9.5.0: CLOUD TYPE + SOLAR PHASE ENRICHMENT
// ============================================================================

/**
 * Cloud-only OWM descriptions that can be replaced with richer cloud-type phrases.
 * Precipitation descriptions (rain, snow, etc.) are left as-is — they carry
 * critical scene information that cloud-type phrases don't cover.
 */
const REPLACEABLE_SKY = new Set([
  'clear sky',
  'clear',
  'sunny',
  'few clouds',
  'scattered clouds',
  'broken clouds',
  'overcast clouds',
  'overcast',
  'partly cloudy',
  'mostly cloudy',
  'cloudy',
]);

/**
 * When sky source is a generic OWM cloud description, replace with the
 * richer cloud-type-specific phrase from cloud-types.ts.
 * Precipitation descriptions pass through untouched.
 * null stays null (lighting already encodes cloud state).
 */
function enhanceSkySource(
  skySource: string | null,
  visualTruth: VisualTruth | null,
  seed: number,
): string | null {
  if (!skySource) return null;
  if (!visualTruth?.cloudType) return skySource;

  const lower = skySource.toLowerCase().trim();
  if (REPLACEABLE_SKY.has(lower)) {
    return getCloudTypePhrase(visualTruth.cloudType as CloudType, seed);
  }
  return skySource;
}

/**
 * Enhance time descriptor with solar phase label when at dawn/dusk.
 * "Late afternoon" → "Sunset golden hour, late afternoon"
 */
function enhanceTimeWithPhase(time: string, visualTruth: VisualTruth | null): string {
  if (!visualTruth?.solarPhase) return time;
  const label = getSolarPhaseLabel(visualTruth.solarPhase as SolarPhase);
  if (!label) return time;
  return `${label}, ${time.charAt(0).toLowerCase() + time.slice(1)}`;
}

// ============================================================================
// TIER 1: CLIP-Based — Weighted keywords for Stable Diffusion / Leonardo / ComfyUI
// ============================================================================
// + Flux variant (T5 encoder) generated by generateTier1Flux() below.
// ============================================================================

export function generateTier1(
  city: string,
  weather: ExchangeWeatherFull,
  hour: number,
  lighting: LightingState,
  observedAtUtc: Date,
  visualTruth: VisualTruth | null,
  venue: VenueResult | null,
  profile: PromptProfile,
): WeatherPromptResult {
  const ctx = buildContext(weather, hour, observedAtUtc);
  const seed = computeSeed(ctx, hour, observedAtUtc, city);

  const quiet = shouldExcludePeople(profile, weather, hour, observedAtUtc);
  const wind = getWindPhrase(ctx, seed, venue?.setting, visualTruth?.precip);
  const time = getTimeDescriptor(ctx, seed);
  const skySource = getSkySourceAware(ctx, seed, lighting.encodesCloudState);

  // v9.5.0: Cloud type + solar phase enrichment
  const enrichedSky = enhanceSkySource(skySource, visualTruth, seed);
  const enrichedTime = enhanceTimeWithPhase(time, visualTruth);

  // v7.0: Visual truth phrases (optical effects) instead of weather-report phrases
  const moisture = visualTruth
    ? getMoisturePhrase(visualTruth, seed, venue?.setting)
    : getHumidityPhrase(ctx, seed);
  const thermal = visualTruth ? getThermalPhrase(visualTruth, seed) : getTempPhrase(ctx, seed);
  const grounding = visualTruth
    ? getSurfaceGrounding(visualTruth, ctx.tempC, moisture, thermal, seed, venue?.setting)
    : null;

  // Lighting: primary source gets 1.3, modifiers unweighted comma tokens
  const lightingParts: string[] = [];
  lightingParts.push(`(${lighting.base}:1.3)`);
  if (lighting.shadowModifier) lightingParts.push(lighting.shadowModifier);
  if (lighting.atmosphereModifier) lightingParts.push(lighting.atmosphereModifier);
  // Stability modifier omitted from T1 — too abstract for CLIP

  // v9.2.0: Camera-enriched quality tags replace static STYLE_QUALITY_TAGS
  const camera = getCameraLens(profile.style, venue?.setting ?? null, seed);
  const qualityTags = getQualityTagsT1(camera, profile.style);

  const parts: (string | null)[] = [
    `(${city}:1.3)`,
    venue ? `(${venue.name}:1.2)` : null,
    ...lightingParts,
    lighting.moonVisible
      ? `(${ctx.moonPhrase}${lighting.moonPositionPhrase ? ' ' + lighting.moonPositionPhrase : ''}:1.2)`
      : null,
    enrichedSky ? `(${enrichedSky}:1.1)` : null,
    thermal,
    wind,
    moisture,
    grounding,
    enrichedTime,
    ...qualityTags,
  ];

  // v8.0.0 Chat 7: Fragment limit driven by profile.verbosity.
  const maxParts = VERBOSITY_T1_LIMIT[profile.verbosity];
  const filtered = parts.filter(Boolean) as string[];
  while (filtered.length > maxParts) {
    const dropIdx = filtered.length - qualityTags.length - 1;
    if (dropIdx < 3) break; // Never drop city/venue/primary lighting
    filtered.splice(dropIdx, 1);
  }

  const positivePrompt = filtered.join(', ');
  // v9.2.0: Platform-aware negative prompt (richer CLIP anti-tokens)
  const negativePrompt = getNegativeT1(quiet);

  return {
    text: `Positive prompt: ${positivePrompt}\nNegative prompt: ${negativePrompt}`,
    positive: positivePrompt,
    negative: negativePrompt,
    tier: 1,
  };
}

// ============================================================================
// TIER 1F: Flux-Native Variant — T5 Text Encoder (v9.6.0 Chat 7)
// ============================================================================
//
// PROBLEM: Flux uses a T5 text encoder, NOT CLIP. T5 doesn't understand:
//   - (token:1.3) weight syntax — sees parentheses as literal text
//   - Negative prompts — Flux has no CFG-based negative prompt support
//
// SOLUTION: Generate a clean variant that strips weights, joins as flowing
// descriptive text, weaves camera naturally, and omits negative prompts.
// This is returned in WeatherPromptResult.fluxPrompt alongside the CLIP version.
//
// T5 strengths: long-form comprehension, adjective ordering, spatial relations.
// Lean into those: use natural adjective chains and "X with Y" constructions.

/**
 * Strip CLIP weight syntax from a token.
 * "(golden hour light:1.3)" → "golden hour light"
 * "sharp focus" → "sharp focus" (unchanged)
 */
function stripClipWeight(token: string): string {
  const match = token.match(/^\((.+?)(?::\d+(?:\.\d+)?)\)$/);
  return match?.[1] ?? token;
}

/**
 * Generate a Flux-native (T5 encoder) variant of a Tier 1 prompt.
 * Same data as CLIP Tier 1 but formatted for T5 comprehension.
 */
export function generateTier1Flux(
  city: string,
  weather: ExchangeWeatherFull,
  hour: number,
  lighting: LightingState,
  observedAtUtc: Date,
  visualTruth: VisualTruth | null,
  venue: VenueResult | null,
  profile: PromptProfile,
): string {
  const ctx = buildContext(weather, hour, observedAtUtc);
  const seed = computeSeed(ctx, hour, observedAtUtc, city);

  const wind = getWindPhrase(ctx, seed, venue?.setting, visualTruth?.precip);
  const time = getTimeDescriptor(ctx, seed);
  const skySource = getSkySourceAware(ctx, seed, lighting.encodesCloudState);

  // v9.5.0: Cloud type + solar phase enrichment
  const enrichedSky = enhanceSkySource(skySource, visualTruth, seed);
  const enrichedTime = enhanceTimeWithPhase(time, visualTruth);

  // Visual truth phrases
  const moisture = visualTruth
    ? getMoisturePhrase(visualTruth, seed, venue?.setting)
    : getHumidityPhrase(ctx, seed);
  const thermal = visualTruth ? getThermalPhrase(visualTruth, seed) : getTempPhrase(ctx, seed);
  const grounding = visualTruth
    ? getSurfaceGrounding(visualTruth, ctx.tempC, moisture, thermal, seed, venue?.setting)
    : null;

  // Lighting: clean base phrase without CLIP modifiers
  const lightBase = lighting.base;
  const lightMods = [lighting.shadowModifier, lighting.atmosphereModifier].filter(Boolean);
  const lightPhrase = lightMods.length ? `${lightBase} with ${lightMods.join(' and ')}` : lightBase;

  // Moon
  const moonPart = lighting.moonVisible
    ? lighting.moonPositionPhrase
      ? `${ctx.moonPhrase} ${lighting.moonPositionPhrase}`
      : ctx.moonPhrase
    : null;

  // Camera: "professional photography on Canon EOS R5, 35mm f/1.4"
  const camera = getCameraLens(profile.style, venue?.setting ?? null, seed);
  const cameraNatural = `${camera.body} with ${camera.lensSpec} lens`;

  // Build flowing T5-friendly prompt
  // T5 excels at understanding natural adjective chains and spatial relations
  const venuePart = venue ? ` at ${venue.name}` : '';
  const parts: (string | null)[] = [
    `${city}${venuePart}`,
    enrichedTime,
    lightPhrase,
    enrichedSky,
    moonPart,
    thermal,
    wind,
    moisture,
    grounding,
    `professional photography, ${cameraNatural}`,
  ];

  // Strip any CLIP weights that leaked through from phrase pools
  const cleaned = parts
    .filter(Boolean)
    .map((p) => stripClipWeight(p as string))
    .join(', ');

  return cleaned;
}

// ============================================================================
// TIER 2: Midjourney — V6.1/V7 Natural Language + Legacy V5.2 (v9.6.0)
// ============================================================================
//
// V6.1/V7: Natural language flow, period-separated scene breaks.
// V5.2 (legacy): Multi-prompt with :: weights for backward compat.
//
// Word budget: V7 ~75 words, V6.1 ~60 words (MJ docs warn long prompts confuse).
//
// v9.2.0:
// - Camera body appended (MJ interprets camera look natively)
// - --no fix: proper space-separated tokens, no commas, richer list
// v9.6.0:
// - --v param added (5.2, 6.1, 7)
// - V6.1/V7: natural language replaces :: multi-prompt syntax

export function generateTier2(
  city: string,
  weather: ExchangeWeatherFull,
  hour: number,
  lighting: LightingState,
  observedAtUtc: Date,
  visualTruth: VisualTruth | null,
  solarElevation: number | null,
  venue: VenueResult | null,
  profile: PromptProfile,
): string {
  const ctx = buildContext(weather, hour, observedAtUtc);
  const seed = computeSeed(ctx, hour, observedAtUtc, city);

  const quiet = shouldExcludePeople(profile, weather, hour, observedAtUtc);
  const wind = getWindPhrase(ctx, seed, venue?.setting, visualTruth?.precip);
  const time = getTimeDescriptor(ctx, seed);
  const skySource = getSkySourceAware(ctx, seed, lighting.encodesCloudState);

  // v9.5.0: Cloud type + solar phase enrichment
  const enrichedSky = enhanceSkySource(skySource, visualTruth, seed);
  const enrichedTime = enhanceTimeWithPhase(time, visualTruth);

  // Visual truth phrases
  const moisture = visualTruth
    ? getMoisturePhrase(visualTruth, seed, venue?.setting)
    : getHumidityPhrase(ctx, seed);
  const thermal = visualTruth ? getThermalPhrase(visualTruth, seed) : getTempPhrase(ctx, seed);
  const grounding = visualTruth
    ? getSurfaceGrounding(visualTruth, ctx.tempC, moisture, thermal, seed, venue?.setting)
    : null;

  // Connected lighting (thermal absorbed as connector)
  const lightScene = composeLightingSentence(lighting, visualTruth, seed);

  // Moon
  const moonPart = lighting.moonVisible
    ? lighting.moonPositionPhrase
      ? `${ctx.moonPhrase} ${lighting.moonPositionPhrase}`
      : ctx.moonPhrase
    : null;

  // Surface with light reflection reference
  const isNight = lighting.nightDominant !== null;
  const urbanFactor = getUrbanLightFactor(city);
  const lightRef = getLightReflectionNoun(
    isNight,
    urbanFactor,
    solarElevation,
    seed,
    venue?.setting,
  );
  const moistureLevel = visualTruth?.moistureVisibility ?? 'invisible';
  const surfacePhrase = composeSurfaceSentence(moisture, grounding, moistureLevel, lightRef);

  // v9.2.0: Camera body for MJ colour science
  const camera = getCameraLens(profile.style, venue?.setting ?? null, seed);
  const cameraTag = getQualityT2(camera);

  // ── v9.6.0: MJ Version-aware prompt format ────────────────────────────
  const noParam = getMjNoParam(quiet);
  const versionParam = `--v ${profile.mjVersion}`;
  const params = `--ar ${profile.mjAspect} --stylize ${profile.mjStylize} ${versionParam} ${noParam}`;

  if (profile.mjVersion === '5.2') {
    // ── Legacy V5.2: Multi-prompt with :: weights ──────────────────────
    const seg1 = `${capitalize(enrichedTime)}, ${lightScene}, ${cameraTag}`;
    const venuePart = venue ? ` at ${venue.name}` : '';
    const sceneParts = [`${city}${venuePart}`, enrichedSky, moonPart, wind].filter(Boolean);
    const seg2 = sceneParts.join(', ');
    const surfaceLower = surfacePhrase
      ? surfacePhrase.charAt(0).toLowerCase() + surfacePhrase.slice(1)
      : null;
    const countWords = (s: string) => s.split(/\s+/).length;
    const baseWords = countWords(seg1) + countWords(seg2);
    const surfaceWords = surfaceLower ? countWords(surfaceLower) : 0;

    let prompt: string;
    if (surfaceLower && baseWords + surfaceWords <= 45) {
      prompt = `${seg1}::2 ${seg2}::1 ${surfaceLower}::0.5`;
    } else {
      prompt = `${seg1}::2 ${seg2}::1`;
    }
    return `${prompt} ${params}`;
  }

  // ── Modern V6.1/V7: Natural language flow ────────────────────────────
  // MJ V6+ interprets natural language directly. No :: weights needed.
  // Structure: Location + time. Lighting + atmosphere. Surface + wind. Camera.
  //
  // v9.8.0 fixes:
  // - Time: Use solar phase label alone when available. Avoids redundant
  //   "Deep dusk, early evening" — MJ averages conflicting time cues.
  // - Moon: Phase + simple visibility, no cardinal direction. MJ can't
  //   interpret "mid-sky in the western sky"; it wastes word budget.
  // - Structure: subject/location → lighting → atmosphere → camera (MJ-optimal order)

  // v9.8.0: MJ-optimised time — solar phase label alone, or time descriptor
  const solarLabel = visualTruth?.solarPhase
    ? getSolarPhaseLabel(visualTruth.solarPhase as SolarPhase)
    : null;
  const mjTime = solarLabel ? capitalize(solarLabel) : capitalize(time);

  // v9.8.0: MJ-optimised moon — phase + simple visibility, no cardinal direction.
  // "above the rooftops" works universally (skyline doesn't fit squares/parks/monuments).
  const mjMoon = lighting.moonVisible
    ? `${ctx.moonPhrase} moon visible above the rooftops`
    : null;

  const venuePart = venue ? ` at ${venue.name}` : '';
  const sceneParts = [enrichedSky, mjMoon, wind].filter(Boolean);
  const sceneTrail = sceneParts.length > 0 ? `, ${sceneParts.join(', ')}` : '';

  // S1: Location + time + scene elements
  const s1 = `${city}${venuePart}, ${mjTime.charAt(0).toLowerCase() + mjTime.slice(1)}${sceneTrail}`;

  // S2: Lighting as a connected sentence
  const s2 = `${capitalize(lightScene)}`;

  // S3: Surface detail (optional, word-budget aware)
  const surfaceLower = surfacePhrase
    ? surfacePhrase.charAt(0).toLowerCase() + surfacePhrase.slice(1)
    : null;

  // S4: Camera tag (now includes lens spec)
  const s4 = `Photorealistic, ${cameraTag}`;

  // Assemble with period separators (MJ V6/V7 reads periods as scene breaks)
  const sentences = [s1, s2, surfaceLower, s4].filter(Boolean);

  // Word budget: MJ V7 handles ~75 words well; V6.1 prefers ~60
  const wordLimit = profile.mjVersion === '7' ? 75 : 60;
  let prompt = sentences.join('. ');

  // Trim from the end if over budget (drop surface first, then camera)
  const countWords = (s: string) => s.split(/\s+/).length;
  if (countWords(prompt) > wordLimit && surfaceLower) {
    const trimmed = [s1, s2, s4].filter(Boolean);
    prompt = trimmed.join('. ');
  }
  if (countWords(prompt) > wordLimit) {
    prompt = [s1, s2].filter(Boolean).join('. ');
  }

  return `${prompt} ${params}`;
}

// ============================================================================
// TIER 3: Natural Language — Connected scene description (DEFAULT TIER)
// ============================================================================
//
// STRUCTURE:
//   S1: Location + time anchor (direct nouns, no filler)
//   S2: Connected lighting scene + sky + moon
//   S3: Wind as action
//   S4: Surface reflecting specific light
//   S5: Quality directive + camera metadata + quiet hours
//
// v9.2.0:
// - Camera metadata appended to setting ending as "Shot on X with Y lens."
// - "Avoid:" sentence replaces blunt "No people" when quiet (DALL·E/Imagen
//   respond better to avoidance framing than prohibition)

export function generateTier3(
  city: string,
  weather: ExchangeWeatherFull,
  hour: number,
  lighting: LightingState,
  observedAtUtc: Date,
  visualTruth: VisualTruth | null,
  solarElevation: number | null,
  venue: VenueResult | null,
  profile: PromptProfile,
): string {
  const ctx = buildContext(weather, hour, observedAtUtc);
  const seed = computeSeed(ctx, hour, observedAtUtc, city);

  const quiet = shouldExcludePeople(profile, weather, hour, observedAtUtc);
  const wind = getWindPhrase(ctx, seed, venue?.setting, visualTruth?.precip);
  const time = getTimeDescriptor(ctx, seed);
  const skySource = getSkySourceAware(ctx, seed, lighting.encodesCloudState);

  // v9.5.0: Cloud type + solar phase enrichment
  const enrichedSky = enhanceSkySource(skySource, visualTruth, seed);
  const enrichedTime = enhanceTimeWithPhase(time, visualTruth);

  // Visual truth phrases
  const moisture = visualTruth
    ? getMoisturePhrase(visualTruth, seed, venue?.setting)
    : getHumidityPhrase(ctx, seed);
  const thermal = visualTruth ? getThermalPhrase(visualTruth, seed) : getTempPhrase(ctx, seed);
  const grounding = visualTruth
    ? getSurfaceGrounding(visualTruth, ctx.tempC, moisture, thermal, seed, venue?.setting)
    : null;

  // ── S1: Location + time anchor ──────────────────────────────────────
  const venuePart = venue ? `, ${venue.name}` : '';
  const opening = `${city}${venuePart}, ${enrichedTime}.`;

  // ── S2: Connected lighting scene ────────────────────────────────────
  const lightScene = composeLightingSentence(lighting, visualTruth, seed);
  const skyClause = enrichedSky ? ` ${capitalize(enrichedSky)} overhead.` : '';
  let moonClause = '';
  if (lighting.moonVisible) {
    moonClause = lighting.moonPositionPhrase
      ? ` A ${ctx.moonPhrase} ${lighting.moonPositionPhrase}.`
      : ` Under a ${ctx.moonPhrase}.`;
  }
  const lightSentence = `${capitalize(lightScene)}.${skyClause}${moonClause}`;

  // ── S3: Wind as action ──────────────────────────────────────────────
  let windSentence = '';
  const speed = Math.round(ctx.windKmh);
  if (speed >= 6) {
    windSentence = `${capitalize(wind)}.`;
  }

  // ── S4: Surface reflecting light ────────────────────────────────────
  const isNight = lighting.nightDominant !== null;
  const urbanFactor = getUrbanLightFactor(city);
  const lightRef = getLightReflectionNoun(
    isNight,
    urbanFactor,
    solarElevation,
    seed,
    venue?.setting,
  );
  const moistureLevel = visualTruth?.moistureVisibility ?? 'invisible';
  const surfacePhrase = composeSurfaceSentence(moisture, grounding, moistureLevel, lightRef);
  const surfaceSentence = surfacePhrase ? `${surfacePhrase}.` : '';

  // ── S5: Quality + Camera + quiet ────────────────────────────────────
  // v9.2.0: Camera metadata appended after setting ending.
  const camera = getCameraLens(profile.style, venue?.setting ?? null, seed);
  const cameraEnding = getQualityEndingT3(camera);

  const sentences = [
    opening,
    lightSentence,
    windSentence,
    surfaceSentence,
    getSettingEnding(venue, profile.style),
    cameraEnding,
  ].filter(Boolean);

  // v9.2.0: "Avoid:" framing for NL platforms (DALL·E, Imagen, Firefly)
  if (quiet) sentences.push('Avoid showing people, text, or watermarks.');

  return sentences.join(' ');
}

// ============================================================================
// TIER 4: Plain Language — Simple comma-separated prompt
// ============================================================================
//
// v9.2.0:
// - Lens descriptor added to fragments ("wide angle", "35mm prime")
// - Negative suffix richer: "no people, no text, no watermarks"

export function generateTier4(
  city: string,
  weather: ExchangeWeatherFull,
  hour: number,
  lighting: LightingState,
  observedAtUtc: Date,
  visualTruth: VisualTruth | null,
  venue: VenueResult | null,
  profile: PromptProfile,
): string {
  const ctx = buildContext(weather, hour, observedAtUtc);
  const seed = computeSeed(ctx, hour, observedAtUtc, city);

  const quiet = shouldExcludePeople(profile, weather, hour, observedAtUtc);
  const wind = getWindPhrase(ctx, seed, venue?.setting, visualTruth?.precip);
  const time = getTimePeriod(ctx.hour);
  const skySource = getSkySourceAware(ctx, seed, lighting.encodesCloudState);

  // v9.5.0: Cloud type enrichment (solar phase label skipped — T4 uses simple periods)
  const enrichedSky = enhanceSkySource(skySource, visualTruth, seed);

  // ── v9.7.0: Weather-event placement fix ─────────────────────────────
  // Some OpenWeather descriptions are single phenomenon words ("rain", "storm",
  // "snow", "mist", etc.). In Tier 4 (comma-separated), low-priority sky tokens
  // naturally drift to the end, producing awkward tails like:
  //   "..., 35mm prime, rain"
  // These are not wrong semantically, but they read like a dangling afterthought
  // and reduce prompt interpretability for simpler parsers.
  //
  // Fix: Treat precipitation/visibility phenomena as high-salience "event" tokens
  // and place them near the lighting/time anchor.
  function isWeatherEventToken(s: string): boolean {
    const t = s.toLowerCase().trim();
    // Single-word or short phenomenon phrases that should sit early.
    // (We keep this intentionally conservative to avoid moving descriptive cloud types.)
    return (
      t === 'rain' ||
      t === 'snow' ||
      t === 'sleet' ||
      t === 'hail' ||
      t === 'storm' ||
      t === 'thunderstorm' ||
      t === 'drizzle' ||
      t === 'mist' ||
      t === 'fog' ||
      t === 'haze' ||
      t === 'smoke' ||
      t === 'dust' ||
      t === 'sand' ||
      t === 'ash' ||
      t === 'squall' ||
      t === 'tornado' ||
      // Common short variants from OWM / normalisation.
      t.endsWith(' rain') ||
      t.endsWith(' snow') ||
      t.includes('thunder') ||
      t.includes('storm') ||
      t.includes('freezing')
    );
  }
  const skyPriority = enrichedSky && isWeatherEventToken(enrichedSky) ? 7.2 : 2;

  // Visual truth phrases
  const moisture = visualTruth
    ? getMoisturePhrase(visualTruth, seed, venue?.setting)
    : getHumidityPhrase(ctx, seed);
  const thermal = visualTruth ? getThermalPhrase(visualTruth, seed) : getTempPhrase(ctx, seed);
  const grounding = visualTruth
    ? getSurfaceGrounding(visualTruth, ctx.tempC, moisture, thermal, seed, venue?.setting)
    : null;

  const moonPart = lighting.moonVisible
    ? lighting.moonPositionPhrase
      ? `${ctx.moonPhrase} ${lighting.moonPositionPhrase}`
      : ctx.moonPhrase
    : null;

  // v9.2.0: Camera lens descriptor for weak parsers
  const camera = getCameraLens(profile.style, venue?.setting ?? null, seed);
  const lensPart = getQualityT4(camera);

  // Priority-tagged parts for the fragment limit.
  const tagged: { value: string | null | undefined; priority: number }[] = [
    { value: city, priority: 10 },
    { value: venue?.name, priority: 9 },
    { value: lighting.fullPhrase, priority: 8 },
    { value: time, priority: 7 },
    // v9.7.0: If sky token is a precip/phenomenon ("rain", "storm", etc.),
    // prioritise it so it appears near the lighting/time anchor.
    { value: enrichedSky, priority: skyPriority },
    { value: wind, priority: 6 },
    { value: moisture, priority: 5 },
    { value: thermal, priority: 4 },
    { value: lensPart, priority: 3.5 }, // v9.2.0: lens descriptor
    { value: moonPart, priority: 3 },
    { value: grounding, priority: 1 },
  ];

  const live = tagged.filter((t): t is { value: string; priority: number } => !!t.value);

  const MAX_T4_PARTS = VERBOSITY_T4_LIMIT[profile.verbosity];
  while (live.length > MAX_T4_PARTS) {
    let minIdx = 0;
    let minPri = live[0]?.priority ?? Infinity;
    for (let i = 1; i < live.length; i++) {
      const pri = live[i]?.priority ?? Infinity;
      if (pri < minPri) {
        minPri = pri;
        minIdx = i;
      }
    }
    live.splice(minIdx, 1);
  }

  const prompt = live.map((t) => t.value).join(', ');
  return quiet ? `${prompt}, no people, no text, no watermarks` : prompt;
}

// ============================================================================
// HELPERS
// ============================================================================
