#!/usr/bin/env ts-node
// scripts/generate-code-dates.ts
// ============================================================================
// GIT-AWARE CONFIDENCE — Build-time date generator
// ============================================================================
//
// Reads `git log` for each monitored pipeline file and writes a TypeScript
// module with last-modified dates + commit counts.
//
// Usage (PowerShell, at repo root):
//   npx ts-node scripts/generate-code-dates.ts
//
// Or add to package.json:
//   "generate:code-dates": "ts-node scripts/generate-code-dates.ts"
//
// Output: src/lib/admin/code-dates.generated.ts
//
// Authority: Phase 7.11j — Code Evolution Radar — Git-Aware Confidence
//
// Version: 1.0.0
// Created: 2026-03-01
// ============================================================================

 

import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

// ── Monitored files (relative to repo root) ────────────────────────────
// Each key is the Radar file label.  Values are candidate paths to check
// in order (the first one found in git wins).
const MONITORED_FILES: Record<string, string[]> = {
  'weight-recalibration.ts': [
    'src/lib/learning/weight-recalibration.ts',
  ],
  'outcome-score.ts': [
    'src/lib/learning/outcome-score.ts',
  ],
  'anti-pattern-detection.ts': [
    'src/lib/learning/anti-pattern-detection.ts',
    'src/lib/learning/anti-pattern-detector.ts',
  ],
  'vocabulary system': [
    'src/lib/vocabulary/vocabulary-service.ts',
    'src/lib/vocabulary/categories.ts',
    'src/lib/vocabulary/index.ts',
  ],
  'temporal-intelligence.ts': [
    'src/lib/learning/temporal-intelligence.ts',
  ],
};

interface GitInfo {
  lastModified: string;
  commitMessage: string;
  commits: number;
}

function getGitInfo(filePaths: string[]): GitInfo | null {
  for (const filePath of filePaths) {
    try {
      // Last modified date (author date, ISO format)
      const dateStr = execSync(
        `git log -1 --format="%aI" -- "${filePath}"`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
      ).trim();

      if (!dateStr) continue;

      // Last commit subject line
      const message = execSync(
        `git log -1 --format="%s" -- "${filePath}"`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
      ).trim();

      // Total commits touching this file
      const countStr = execSync(
        `git rev-list --count HEAD -- "${filePath}"`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
      ).trim();

      return {
        lastModified: dateStr.slice(0, 10), // YYYY-MM-DD
        commitMessage: message.slice(0, 120),
        commits: parseInt(countStr, 10) || 1,
      };
    } catch {
      // File may not exist in git history — try next candidate
      continue;
    }
  }
  return null;
}

function main(): void {
  console.log('📡 Code Evolution Radar — Generating code dates from git…\n');

  const entries: Record<string, GitInfo> = {};
  const fallbackDate = new Date().toISOString().slice(0, 10);

  for (const [key, paths] of Object.entries(MONITORED_FILES)) {
    const result = getGitInfo(paths);
    if (result) {
      entries[key] = result;
      console.log(`  ✅ ${key.padEnd(30)} ${result.lastModified}  (${result.commits} commits)`);
    } else {
      entries[key] = {
        lastModified: fallbackDate,
        commitMessage: 'No git history found — using today as fallback',
        commits: 0,
      };
      console.log(`  ⚠️ ${key.padEnd(30)} ${fallbackDate}  (no git history)`);
    }
  }

  // ── Write TypeScript module ──────────────────────────────────────────
  const output = `// src/lib/admin/code-dates.generated.ts
// ============================================================================
// AUTO-GENERATED by scripts/generate-code-dates.ts — Do not edit manually.
// Generated: ${new Date().toISOString()}
// ============================================================================

export interface CodeDateEntry {
  /** YYYY-MM-DD date when this file was last modified in git */
  lastModified: string;
  /** Last commit message touching this file */
  commitMessage: string;
  /** Total number of commits to this file */
  commits: number;
}

/**
 * Git-derived last-modified dates for monitored pipeline files.
 * Used by the Code Evolution Radar to compute Confidence Thermometer decay.
 */
export const CODE_DATES: Record<string, CodeDateEntry> = ${JSON.stringify(entries, null, 2)};

/**
 * Estimated data volume at time of last code change.
 * Updated manually or via build-time DB query.
 */
export const DATA_VOLUME_AT_WRITE: Record<string, number> = {
  'weight-recalibration.ts': 5000,
  'outcome-score.ts': 5000,
  'anti-pattern-detection.ts': 3000,
  'vocabulary system': 8000,
  'temporal-intelligence.ts': 10000,
};
`;

  const outPath = resolve(__dirname, '../src/lib/admin/code-dates.generated.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(`\n✅ Written to ${outPath}`);
}

main();
