name: CI - Lint and Build

on:
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # <— run all steps inside /frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint (named exports enforced in src/**)
        run: npm run lint

      - name: Build
        run: npm run build

