name: CI - Lint and Build

on:
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # --- Debug: prove we are in the right folder and lockfile exists ---
      - name: Show working dir and files
        run: |
          pwd
          ls -la
          test -f package.json && echo "package.json OK" || (echo "package.json MISSING" && exit 1)
          test -f package-lock.json && echo "package-lock.json OK" || (echo "lockfile MISSING" && exit 1)

      - name: Install dependencies
        run: npm ci || npm install

      - name: Show node_modules existence + eslint version
        run: |
          ls -la node_modules | head -n 20
          npx --yes eslint -v

      - name: Lint (named exports enforced in src/**)
        run: npm run lint

      - name: Build
        run: npm run build
