name: CI

on:
  push:
    branches:
      - main
      - ci/sanity
      - feat/*
      - fix/*
    paths:
      - "frontend/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
      - ci/sanity
      - feat/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup pnpm first so setup-node can use its cache safely
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Setup Node.js with pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Lint source files
      - name: Lint
        run: pnpm exec eslint "src/**/*.{ts,tsx}" -f stylish

      # Type check
      - name: Typecheck
        run: pnpm run typecheck

      # Build
      - name: Build
        run: pnpm run build

