// src/data/community-pulse/demo-prompts.json.d.ts
// Type declaration for the 210 pre-generated demo prompts.
// Generated by scripts/generate-demo-prompts.ts — do not edit by hand.

interface DemoPromptEntry {
  platformId: string;
  platformName: string;
  platformIcon: string;
  brandColor: string;
  description: string;
  optimisedPrompt: string;
  score: number;
  countryCode: string;
  locationName: string;
  likeCount: number;
}

declare const demoPrompts: DemoPromptEntry[];
export default demoPrompts;
