app = "promagen-api"
primary_region = "lhr"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 40

  [[http_service.checks]]
    interval = "10s"
    timeout = "3s"
    grace_period = "45s"
    method = "GET"
    path = "/health"
