name: audit-verify
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    env:
      NODE_ENV: test
      PORT: 3001
      DATABASE_URL: "file:./dev.db"
      PRISMA_SCHEMA: "./prisma/schema.sqlite.prisma"
      AUDIT_HMAC_SECRET: "ci-secret-please-rotate"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - run: npm ci
      - run: npx prisma db push --schema=$PRISMA_SCHEMA --force-reset
      - run: npx prisma generate --schema=$PRISMA_SCHEMA

      - name: Start API
        run: |
          npx tsx src/server.ts & 
          echo $! > server.pid
          sleep 2

      - name: Health
        run: curl -sSf http://localhost:3001/health

      - name: Post bulk (JSON)
        run: |
          BODY='{"base":72,"bases":{"openai":80,"midjourney":78}}'
          curl -sSf -X POST -H "Content-Type: application/json" \
            --data "$BODY" "http://localhost:3001/api/v1/providers/leaderboard/bulk?format=csv&reviewer=CI&period=auto" \
            -o /tmp/leaderboard.csv
          head -n 6 /tmp/leaderboard.csv

      - name: Verify list status
        run: |
          LIST=$(curl -sSf http://localhost:3001/api/v1/audit)
          echo "$LIST" | jq .
          SHA=$(echo "$LIST" | jq -r '.items[0].shaValid')
          HMAC=$(echo "$LIST" | jq -r '.items[0].hmacValid')
          if [ "$SHA" != "true" ]; then echo "SHA verify failed"; exit 1; fi
          if [ "$HMAC" != "true" ]; then echo "HMAC verify failed"; exit 1; fi

      - name: Stop API
        if: always()
        run: kill $(cat server.pid) || true
