name: ci-frontend
on:
  push:
    branches: [ feat/vercel-frontend ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - uses: pnpm/action-setup@v4
        with: { version: 10.18.2 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install
        run: pnpm -C frontend install --frozen-lockfile
      - name: Lint
        run: pnpm -C frontend lint
      - name: Build
        run: pnpm -C frontend build