name: check-frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install pnpm first so setup-node can cache properly
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # Use the workspace lockfile at repo root, but install only the frontend project
      - name: Install (frozen, no scripts)
        run: pnpm -C frontend install --frozen-lockfile --ignore-scripts

      - name: Sanity
        run: pnpm -C frontend exec node -v

      - name: Lint (non-blocking)
        run: pnpm -C frontend run lint || echo "lint failed (non-blocking)"
