name: Lint
on:
  push:
    branches: [ "**" ]
    paths:
      - "frontend/**"
      - ".github/workflows/lint.yml"
      - ".github/eslint-problem-matcher.json"
      - "frontend/eslint.config.mjs"
      - "frontend/package.json"
      - "frontend/tsconfig.json"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/lint.yml"
      - ".github/eslint-problem-matcher.json"
      - "frontend/eslint.config.mjs"
      - "frontend/package.json"
      - "frontend/tsconfig.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: frontend
    env:
      NODE_OPTIONS: "--max-old-space-size=2048"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies (clean)
        run: npm ci --ignore-scripts

      - name: Register ESLint problem matcher
        run: echo "::add-matcher::.github/eslint-problem-matcher.json"

      - name: Lint
        run: npm run lint
