name: update-docs
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions: {}

jobs:
  noop:
    name: Parked (no-op)
    runs-on: ubuntu-latest
    steps:
      - name: Explain status
        run: |
          echo "update-docs workflow is parked. No git pushes from CI."
          echo "Run manually via 'workflow_dispatch' if you add a generator later."
